import type {
  MaterialTemplate,
  ProcedureTemplate,
  ProcedureTemplateMaterial,
} from "@/types/procedure-library";

const STAMP = "2026-10-01T12:00:00.000Z";
const REF_DATE = "2026-09-15";

function mat(
  partial: Omit<MaterialTemplate, "created_at" | "updated_at" | "active" | "template_version"> &
    Partial<Pick<MaterialTemplate, "active" | "template_version">>,
): MaterialTemplate {
  return {
    active: true,
    template_version: 1,
    created_at: STAMP,
    updated_at: STAMP,
    ...partial,
  };
}

function proc(
  partial: Omit<
    ProcedureTemplate,
    "created_at" | "updated_at" | "active" | "template_version" | "short_name" | "subcategory" | "description" | "complexity_level"
  > &
    Partial<
      Pick<
        ProcedureTemplate,
        | "active"
        | "template_version"
        | "short_name"
        | "subcategory"
        | "description"
        | "complexity_level"
      >
    >,
): ProcedureTemplate {
  return {
    short_name: null,
    subcategory: null,
    description: null,
    complexity_level: null,
    active: true,
    template_version: 1,
    created_at: STAMP,
    updated_at: STAMP,
    ...partial,
  };
}

function link(
  id: string,
  procedure_template_id: string,
  material_template_id: string,
  opts: {
    suggested_quantity?: number | null;
    consumption_unit: MaterialTemplate["suggested_consumption_unit"];
    consumption_mode: ProcedureTemplateMaterial["consumption_mode"];
    optional?: boolean;
    clinically_variable?: boolean;
    notes?: string | null;
    sort_order: number;
  },
): ProcedureTemplateMaterial {
  return {
    id,
    procedure_template_id,
    material_template_id,
    suggested_quantity: opts.suggested_quantity ?? null,
    consumption_unit: opts.consumption_unit,
    consumption_mode: opts.consumption_mode,
    optional: opts.optional ?? false,
    clinically_variable: opts.clinically_variable ?? false,
    notes: opts.notes ?? null,
    sort_order: opts.sort_order,
  };
}

export function buildMaterialTemplates(): MaterialTemplate[] {
  return [
    // Descartáveis
    mat({
      id: "mt-luva",
      name: "Luva",
      category: "descartaveis",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 4000,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["luvas", "luva de procedimento", "luva latex", "luva nitrílica"],
      search_terms: "luva luvas epi descartavel",
    }),
    mat({
      id: "mt-mascara",
      name: "Máscara",
      category: "descartaveis",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: 1500,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["mascara", "máscara cirúrgica", "mascara descartavel"],
      search_terms: "mascara máscara epi descartavel",
    }),
    mat({
      id: "mt-gaze",
      name: "Gaze",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 1500,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["gaze esteril", "gaze estéril"],
      search_terms: "gaze esteril descartavel",
    }),
    mat({
      id: "mt-babador",
      name: "Babador",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 2500,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["babador descartavel"],
      search_terms: "babador descartavel",
    }),
    mat({
      id: "mt-sugador",
      name: "Sugador",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 1800,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["sugador saliva", "sugador descartavel"],
      search_terms: "sugador saliva descartavel",
    }),
    mat({
      id: "mt-touca",
      name: "Touca",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 1200,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["touca descartavel"],
      search_terms: "touca descartavel epi",
    }),
    mat({
      id: "mt-prope",
      name: "Propé",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "par",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: 2000,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["prope", "propés"],
      search_terms: "prope propé descartavel",
    }),
    mat({
      id: "mt-campo",
      name: "Campo descartável",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: 3500,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["campo cirurgico", "campo cirúrgico"],
      search_terms: "campo descartavel cirurgico",
    }),
    mat({
      id: "mt-copo",
      name: "Copo descartável",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 800,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["copo"],
      search_terms: "copo descartavel",
    }),
    mat({
      id: "mt-microbrush",
      name: "Microbrush",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 300,
      reference_purchase_price_cents: 5070,
      reference_price_source: "anúncio público — embalagem 300 un (ref. 2026)",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["micro brush", "aplicador", "pincel aplicador", "microaplicador"],
      search_terms: "microbrush micro brush aplicador pincel",
    }),
    mat({
      id: "mt-fio-dental",
      name: "Fio dental",
      category: "descartaveis",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["fio dental", "passa fio"],
      search_terms: "fio dental",
    }),
    mat({
      id: "mt-papel-carbono",
      name: "Papel carbono",
      category: "descartaveis",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["carbono", "papel articular"],
      search_terms: "papel carbono articular",
    }),
    // Dentística
    mat({
      id: "mt-resina",
      name: "Resina composta",
      category: "dentistica",
      suggested_purchase_unit: "seringa",
      suggested_consumption_unit: "g",
      suggested_units_per_purchase_unit: 4,
      reference_purchase_price_cents: 9000,
      reference_price_source: "estimativa de mercado 2026 — marca variável",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["resina", "composto", "resina A2", "filtek"],
      search_terms: "resina composta flow restauradora filtek",
    }),
    mat({
      id: "mt-resina-flow",
      name: "Resina flow",
      category: "dentistica",
      suggested_purchase_unit: "seringa",
      suggested_consumption_unit: "g",
      suggested_units_per_purchase_unit: 2,
      reference_purchase_price_cents: 7000,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["flow", "resina fluida"],
      search_terms: "resina flow fluida",
    }),
    mat({
      id: "mt-acido",
      name: "Ácido fosfórico",
      category: "dentistica",
      suggested_purchase_unit: "seringa",
      suggested_consumption_unit: "ml",
      suggested_units_per_purchase_unit: 3,
      reference_purchase_price_cents: 2400,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["acido", "ácido", "condicionador acido"],
      search_terms: "acido fosforoico condicionador",
    }),
    mat({
      id: "mt-adesivo",
      name: "Adesivo",
      category: "dentistica",
      suggested_purchase_unit: "frasco",
      suggested_consumption_unit: "ml",
      suggested_units_per_purchase_unit: 4,
      reference_purchase_price_cents: 7669,
      reference_price_source: "anúncio público — Ambar 4 ml (ref. 2026); Single Bond 6 g ≈ R$ 183",
      reference_price_date: REF_DATE,
      clinically_variable: false,
      aliases: ["bond", "adesivo dental", "ambar", "single bond"],
      search_terms: "adesivo bond ambar single bond",
    }),
    mat({
      id: "mt-matriz",
      name: "Matriz",
      category: "dentistica",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["matriz metalica", "matriz seccional"],
      search_terms: "matriz seccional metalica",
    }),
    mat({
      id: "mt-cunha",
      name: "Cunha",
      category: "dentistica",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["cunha de madeira", "cunha interproximal"],
      search_terms: "cunha interproximal",
    }),
    mat({
      id: "mt-tira-poliester",
      name: "Tira de poliéster",
      category: "dentistica",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["tira poliester", "matriz poliester"],
      search_terms: "tira poliester",
    }),
    mat({
      id: "mt-disco-acabamento",
      name: "Disco de acabamento",
      category: "dentistica",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["disco sof-lex", "sof lex"],
      search_terms: "disco acabamento polimento",
    }),
    mat({
      id: "mt-pasta-polimento",
      name: "Pasta de polimento",
      category: "dentistica",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "g",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["pasta profilatica", "pasta profilática"],
      search_terms: "pasta polimento profilatica",
    }),
    // Anestesia
    mat({
      id: "mt-anestesioco",
      name: "Tubete anestésico",
      category: "anestesia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "tubete",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: 16000,
      reference_price_source: "estimativa de mercado 2026 — marca/concentração variáveis",
      reference_price_date: REF_DATE,
      clinically_variable: true,
      aliases: ["anestésico", "anestesico", "carpule", "tubete", "anestesia"],
      search_terms: "tubete anestesico carpule anestesia",
    }),
    mat({
      id: "mt-agulha-curta",
      name: "Agulha curta",
      category: "anestesia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 2500,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: true,
      aliases: ["agulha", "agulha gengival"],
      search_terms: "agulha curta anestesia",
    }),
    mat({
      id: "mt-agulha-longa",
      name: "Agulha longa",
      category: "anestesia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: 2800,
      reference_price_source: "estimativa de mercado 2026",
      reference_price_date: REF_DATE,
      clinically_variable: true,
      aliases: ["agulha longa"],
      search_terms: "agulha longa anestesia",
    }),
    mat({
      id: "mt-anestesico-topico",
      name: "Anestésico tópico",
      category: "anestesia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["topico", "benzocaina"],
      search_terms: "anestesico topico benzocaina",
    }),
    // Endodontia
    mat({
      id: "mt-cone-papel",
      name: "Cone de papel",
      category: "endodontia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["cone papel"],
      search_terms: "cone papel endodontia",
    }),
    mat({
      id: "mt-cone-guta",
      name: "Cone de guta-percha",
      category: "endodontia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 60,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["guta", "guta percha"],
      search_terms: "cone guta percha",
    }),
    mat({
      id: "mt-irrigante",
      name: "Irrigante",
      category: "endodontia",
      suggested_purchase_unit: "frasco",
      suggested_consumption_unit: "ml",
      suggested_units_per_purchase_unit: 500,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["hipoclorito", "naocl"],
      search_terms: "irrigante hipoclorito endodontia",
    }),
    mat({
      id: "mt-edta",
      name: "EDTA",
      category: "endodontia",
      suggested_purchase_unit: "frasco",
      suggested_consumption_unit: "ml",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["edta"],
      search_terms: "edta endodontia",
    }),
    mat({
      id: "mt-cimento-obturador",
      name: "Cimento obturador",
      category: "endodontia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["cimento endodontico"],
      search_terms: "cimento obturador endodontia",
    }),
    mat({
      id: "mt-lima-manual",
      name: "Lima manual",
      category: "endodontia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 6,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["lima k", "lima endodontica"],
      search_terms: "lima manual endodontia",
    }),
    mat({
      id: "mt-curativo-intracanal",
      name: "Curativo intracanal",
      category: "endodontia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["hidroxido de calcio", "curativo"],
      search_terms: "curativo intracanal hidroxido",
    }),
    mat({
      id: "mt-material-provisorio",
      name: "Material provisório",
      category: "endodontia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["cimpat", "provisorio"],
      search_terms: "material provisorio selamento",
    }),
    // Cirurgia
    mat({
      id: "mt-fio-sutura",
      name: "Fio de sutura",
      category: "cirurgia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 12,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["sutura", "nylon", "seda"],
      search_terms: "fio sutura cirurgia",
    }),
    mat({
      id: "mt-lamina",
      name: "Lâmina",
      category: "cirurgia",
      suggested_purchase_unit: "caixa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 100,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["lamina bisturi", "lâmina"],
      search_terms: "lamina bisturi cirurgia",
    }),
    mat({
      id: "mt-sugador-cirurgico",
      name: "Sugador cirúrgico",
      category: "cirurgia",
      suggested_purchase_unit: "pacote",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 50,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["sugador cirurgico"],
      search_terms: "sugador cirurgico",
    }),
    mat({
      id: "mt-hemostatico",
      name: "Material hemostático",
      category: "cirurgia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["hemostatico", "esponja hemostatica"],
      search_terms: "hemostatico cirurgia",
    }),
    // Clareamento
    mat({
      id: "mt-gel-clareador",
      name: "Gel clareador",
      category: "clareamento",
      suggested_purchase_unit: "seringa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["gel clareamento", "peroxido"],
      search_terms: "gel clareador clareamento",
    }),
    mat({
      id: "mt-barreira-gengival",
      name: "Barreira gengival",
      category: "clareamento",
      suggested_purchase_unit: "seringa",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["barreira gengival", "gingival barrier"],
      search_terms: "barreira gengival clareamento",
    }),
    mat({
      id: "mt-dessensibilizante",
      name: "Dessensibilizante",
      category: "clareamento",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["dessensibilizante"],
      search_terms: "dessensibilizante sensibilidade",
    }),
    mat({
      id: "mt-moldeira",
      name: "Moldeira / material de placa",
      category: "clareamento",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["placa clareamento", "moldeira"],
      search_terms: "moldeira placa clareamento",
    }),
    // Prótese
    mat({
      id: "mt-silicone",
      name: "Silicone de moldagem",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["silicone", "pv s"],
      search_terms: "silicone moldagem protese",
    }),
    mat({
      id: "mt-alginato",
      name: "Alginato",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "g",
      suggested_units_per_purchase_unit: 450,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["alginato"],
      search_terms: "alginato moldagem",
    }),
    mat({
      id: "mt-fio-retrator",
      name: "Fio retrator",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["retrator"],
      search_terms: "fio retrator protese",
    }),
    mat({
      id: "mt-cimento-provisorio",
      name: "Cimento provisório",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["cimento temp"],
      search_terms: "cimento provisorio",
    }),
    mat({
      id: "mt-cimento-definitivo",
      name: "Cimento definitivo",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["cimento resinoso", "cimento ionomerico"],
      search_terms: "cimento definitivo protese",
    }),
    mat({
      id: "mt-resina-provisoria",
      name: "Resina provisória",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["provisorio coroa"],
      search_terms: "resina provisoria coroa",
    }),
    mat({
      id: "mt-laboratorio",
      name: "Laboratório (custo externo)",
      category: "protese",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "un",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: true,
      aliases: ["lab", "protetico", "protético"],
      search_terms: "laboratorio custo externo protese",
    }),
    // Periodontia
    mat({
      id: "mt-pasta-profilatica",
      name: "Pasta profilática",
      category: "periodontia",
      suggested_purchase_unit: "un",
      suggested_consumption_unit: "g",
      suggested_units_per_purchase_unit: 1,
      reference_purchase_price_cents: null,
      reference_price_source: null,
      reference_price_date: null,
      clinically_variable: false,
      aliases: ["pasta profilaxia"],
      search_terms: "pasta profilatica periodontia",
    }),
  ];
}

export function buildProcedureTemplates(): ProcedureTemplate[] {
  let order = 0;
  const next = () => ++order;
  return [
    // Avaliação e prevenção
    proc({
      id: "pt-consulta-inicial",
      name: "Consulta inicial",
      category: "avaliacao_prevencao",
      default_duration_minutes: 40,
      search_terms: "consulta inicial avaliacao primeira",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-consulta-retorno",
      name: "Consulta de retorno",
      category: "avaliacao_prevencao",
      default_duration_minutes: 20,
      search_terms: "consulta retorno revisao",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-urgencia",
      name: "Atendimento de urgência",
      category: "avaliacao_prevencao",
      default_duration_minutes: 30,
      search_terms: "urgencia emergencia dor",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-profilaxia",
      name: "Profilaxia",
      category: "avaliacao_prevencao",
      default_duration_minutes: 30,
      search_terms: "profilaxia limpeza prevencao",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-fluor",
      name: "Aplicação tópica de flúor",
      category: "avaliacao_prevencao",
      default_duration_minutes: 15,
      search_terms: "fluor fluór aplicacao topica",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-selante",
      name: "Selante",
      category: "avaliacao_prevencao",
      default_duration_minutes: 20,
      search_terms: "selante fissura",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-biofilme",
      name: "Controle de biofilme",
      category: "avaliacao_prevencao",
      default_duration_minutes: 25,
      search_terms: "biofilme placa controle",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-orientacao-higiene",
      name: "Orientação de higiene",
      category: "avaliacao_prevencao",
      default_duration_minutes: 15,
      search_terms: "orientacao higiene escovacao",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Dentística
    proc({
      id: "pt-rest-pequena",
      name: "Restauração em resina — pequena",
      short_name: "Restauração pequena",
      category: "dentistica",
      subcategory: "restauração",
      default_duration_minutes: 30,
      search_terms: "restauracao pequena resina dentistica",
      sort_order: next(),
      complexity_level: "baixa",
      description:
        "Modelo operacional editável para controle de estoque. Não é protocolo clínico.",
    }),
    proc({
      id: "pt-rest-media",
      name: "Restauração em resina — média",
      short_name: "Restauração média",
      category: "dentistica",
      subcategory: "restauração",
      default_duration_minutes: 45,
      search_terms: "restauracao media resina dentistica",
      sort_order: next(),
      complexity_level: "media",
      description:
        "Modelo operacional editável para controle de estoque. Não é protocolo clínico.",
    }),
    proc({
      id: "pt-rest-extensa",
      name: "Restauração em resina — extensa",
      short_name: "Restauração extensa",
      category: "dentistica",
      subcategory: "restauração",
      default_duration_minutes: 60,
      search_terms: "restauracao extensa resina dentistica",
      sort_order: next(),
      complexity_level: "alta",
      description:
        "Modelo operacional editável para controle de estoque. Não é protocolo clínico.",
    }),
    proc({
      id: "pt-rest-anterior",
      name: "Restauração anterior",
      category: "dentistica",
      default_duration_minutes: 45,
      search_terms: "restauracao anterior estetica",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-rest-cervical",
      name: "Restauração cervical",
      category: "dentistica",
      default_duration_minutes: 35,
      search_terms: "restauracao cervical",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-reconstrucao",
      name: "Reconstrução coronária",
      category: "dentistica",
      default_duration_minutes: 60,
      search_terms: "reconstrucao coronaria nucleo",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-reparo-resina",
      name: "Reparo em resina",
      category: "dentistica",
      default_duration_minutes: 25,
      search_terms: "reparo resina",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-faceta-direta",
      name: "Faceta direta em resina",
      category: "dentistica",
      default_duration_minutes: 60,
      search_terms: "faceta direta resina",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-diastema",
      name: "Fechamento de diastema",
      category: "dentistica",
      default_duration_minutes: 45,
      search_terms: "diastema fechamento",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-polimento-rest",
      name: "Ajuste/acabamento/polimento de restauração",
      category: "dentistica",
      default_duration_minutes: 20,
      search_terms: "polimento acabamento ajuste restauracao",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Periodontia
    proc({
      id: "pt-raspagem-supra",
      name: "Raspagem supragengival",
      category: "periodontia",
      default_duration_minutes: 40,
      search_terms: "raspagem supragengival periodontal",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-raspagem-sub",
      name: "Raspagem subgengival",
      category: "periodontia",
      default_duration_minutes: 50,
      search_terms: "raspagem subgengival",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-raspagem-quadrante",
      name: "Raspagem por quadrante",
      category: "periodontia",
      default_duration_minutes: 45,
      search_terms: "raspagem quadrante",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-manutencao-perio",
      name: "Manutenção periodontal",
      category: "periodontia",
      default_duration_minutes: 40,
      search_terms: "manutencao periodontal",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-polimento-perio",
      name: "Polimento periodontal",
      category: "periodontia",
      default_duration_minutes: 25,
      search_terms: "polimento periodontal",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Endodontia
    proc({
      id: "pt-acesso-endo",
      name: "Acesso endodôntico",
      category: "endodontia",
      default_duration_minutes: 40,
      search_terms: "acesso endodontico abertura",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-endo-uni",
      name: "Tratamento endodôntico — unirradicular",
      category: "endodontia",
      default_duration_minutes: 60,
      search_terms: "tratamento endodontico canal unirradicular",
      sort_order: next(),
      complexity_level: "alta",
      description: "Materiais variáveis — confirme no atendimento. Não é protocolo terapêutico.",
    }),
    proc({
      id: "pt-endo-bi",
      name: "Tratamento endodôntico — birradicular",
      category: "endodontia",
      default_duration_minutes: 75,
      search_terms: "tratamento endodontico canal birradicular",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-endo-multi",
      name: "Tratamento endodôntico — multirradicular",
      category: "endodontia",
      default_duration_minutes: 90,
      search_terms: "tratamento endodontico canal multirradicular molar",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-curativo-endo",
      name: "Curativo intracanal",
      category: "endodontia",
      default_duration_minutes: 30,
      search_terms: "curativo intracanal endodontia",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-retratamento",
      name: "Retratamento endodôntico",
      category: "endodontia",
      default_duration_minutes: 90,
      search_terms: "retratamento endodontico",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-obturacao",
      name: "Obturação endodôntica",
      category: "endodontia",
      default_duration_minutes: 45,
      search_terms: "obturacao endodontica",
      sort_order: next(),
      complexity_level: "alta",
    }),
    // Cirurgia
    proc({
      id: "pt-exodontia-simples",
      name: "Exodontia simples",
      category: "cirurgia",
      default_duration_minutes: 30,
      search_terms: "exodontia extracao simples cirurgia",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-exodontia-cirurgica",
      name: "Exodontia cirúrgica",
      category: "cirurgia",
      default_duration_minutes: 60,
      search_terms: "exodontia cirurgica extracao",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-raiz-residual",
      name: "Remoção de raiz residual",
      category: "cirurgia",
      default_duration_minutes: 45,
      search_terms: "raiz residual remocao",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-terceiro-molar",
      name: "Remoção de terceiro molar",
      category: "cirurgia",
      default_duration_minutes: 60,
      search_terms: "sisos terceiro molar extracao",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-sutura",
      name: "Sutura",
      category: "cirurgia",
      default_duration_minutes: 20,
      search_terms: "sutura",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-remocao-sutura",
      name: "Remoção de sutura",
      category: "cirurgia",
      default_duration_minutes: 15,
      search_terms: "remocao sutura pontos",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Clareamento
    proc({
      id: "pt-clareamento-consultorio",
      name: "Clareamento de consultório — sessão",
      category: "clareamento",
      default_duration_minutes: 60,
      search_terms: "clareamento consultorio sessao estetica",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-clareamento-caseiro",
      name: "Clareamento caseiro — confecção de kit",
      category: "clareamento",
      default_duration_minutes: 40,
      search_terms: "clareamento caseiro kit moldeira",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-dessensibilizante",
      name: "Aplicação de dessensibilizante",
      category: "clareamento",
      default_duration_minutes: 20,
      search_terms: "dessensibilizante sensibilidade",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Prótese
    proc({
      id: "pt-preparo-coroa",
      name: "Preparo para coroa",
      category: "protese",
      default_duration_minutes: 60,
      search_terms: "preparo coroa protese",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-coroa-provisoria",
      name: "Coroa provisória",
      category: "protese",
      default_duration_minutes: 40,
      search_terms: "coroa provisoria",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-moldagem",
      name: "Moldagem",
      category: "protese",
      default_duration_minutes: 40,
      search_terms: "moldagem impressao",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-scan-intraoral",
      name: "Escaneamento intraoral",
      category: "protese",
      default_duration_minutes: 30,
      search_terms: "escaneamento scan intraoral digital",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-cimentacao-coroa",
      name: "Cimentação de coroa",
      category: "protese",
      default_duration_minutes: 40,
      search_terms: "cimentacao coroa",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-cimentacao-prov",
      name: "Cimentação provisória",
      category: "protese",
      default_duration_minutes: 25,
      search_terms: "cimentacao provisoria",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-reembasamento",
      name: "Reembasamento",
      category: "protese",
      default_duration_minutes: 40,
      search_terms: "reembasamento protese",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-ajuste-protese",
      name: "Ajuste de prótese",
      category: "protese",
      default_duration_minutes: 20,
      search_terms: "ajuste protese",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-entrega-protese",
      name: "Entrega de prótese",
      category: "protese",
      default_duration_minutes: 30,
      search_terms: "entrega protese",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Implantodontia
    proc({
      id: "pt-instalacao-implante",
      name: "Instalação de implante",
      category: "implantodontia",
      default_duration_minutes: 90,
      search_terms: "implante instalacao",
      sort_order: next(),
      complexity_level: "alta",
      description: "Materiais altamente configuráveis / manuais.",
    }),
    proc({
      id: "pt-reabertura",
      name: "Reabertura",
      category: "implantodontia",
      default_duration_minutes: 30,
      search_terms: "reabertura implante",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-moldagem-implante",
      name: "Moldagem de implante",
      category: "implantodontia",
      default_duration_minutes: 40,
      search_terms: "moldagem implante",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-scan-implante",
      name: "Escaneamento de implante",
      category: "implantodontia",
      default_duration_minutes: 30,
      search_terms: "scan escaneamento implante",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-componente-implante",
      name: "Instalação de componente",
      category: "implantodontia",
      default_duration_minutes: 30,
      search_terms: "componente implante pilar",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-coroa-implante",
      name: "Instalação de coroa sobre implante",
      category: "implantodontia",
      default_duration_minutes: 45,
      search_terms: "coroa sobre implante",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-manutencao-implante",
      name: "Manutenção de implante",
      category: "implantodontia",
      default_duration_minutes: 30,
      search_terms: "manutencao implante",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    // Odontopediatria
    proc({
      id: "pt-consulta-infantil",
      name: "Consulta infantil",
      category: "odontopediatria",
      default_duration_minutes: 30,
      search_terms: "consulta infantil crianca odontopediatria",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-profilaxia-infantil",
      name: "Profilaxia infantil",
      category: "odontopediatria",
      default_duration_minutes: 25,
      search_terms: "profilaxia infantil crianca",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-fluor-infantil",
      name: "Aplicação de flúor (infantil)",
      category: "odontopediatria",
      default_duration_minutes: 15,
      search_terms: "fluor infantil",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-selante-infantil",
      name: "Selante (infantil)",
      category: "odontopediatria",
      default_duration_minutes: 20,
      search_terms: "selante infantil",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-rest-infantil",
      name: "Restauração (infantil)",
      category: "odontopediatria",
      default_duration_minutes: 35,
      search_terms: "restauracao infantil",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-exodontia-deciduo",
      name: "Exodontia de decíduo",
      category: "odontopediatria",
      default_duration_minutes: 25,
      search_terms: "exodontia deciduo dente de leite",
      sort_order: next(),
      complexity_level: "media",
    }),
    // Ortodontia
    proc({
      id: "pt-consulta-orto",
      name: "Consulta ortodôntica",
      category: "ortodontia",
      default_duration_minutes: 20,
      search_terms: "consulta ortodontica aparelho",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-instalacao-aparelho",
      name: "Instalação de aparelho",
      category: "ortodontia",
      default_duration_minutes: 60,
      search_terms: "instalacao aparelho ortodontia",
      sort_order: next(),
      complexity_level: "alta",
    }),
    proc({
      id: "pt-manutencao-orto",
      name: "Manutenção ortodôntica",
      category: "ortodontia",
      default_duration_minutes: 30,
      search_terms: "manutencao ortodontica",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-colagem-bracket",
      name: "Colagem de bracket",
      category: "ortodontia",
      default_duration_minutes: 25,
      search_terms: "colagem bracket",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-reposicao-bracket",
      name: "Reposição de bracket",
      category: "ortodontia",
      default_duration_minutes: 20,
      search_terms: "reposicao bracket",
      sort_order: next(),
      complexity_level: "baixa",
    }),
    proc({
      id: "pt-remocao-aparelho",
      name: "Remoção de aparelho",
      category: "ortodontia",
      default_duration_minutes: 45,
      search_terms: "remocao aparelho",
      sort_order: next(),
      complexity_level: "media",
    }),
    proc({
      id: "pt-contencao",
      name: "Contenção",
      category: "ortodontia",
      default_duration_minutes: 30,
      search_terms: "contencao ortodontia",
      sort_order: next(),
      complexity_level: "baixa",
    }),
  ];
}

/** EPI básico por atendimento */
function epiLinks(
  procId: string,
  startOrder: number,
): ProcedureTemplateMaterial[] {
  return [
    link(`${procId}-luva`, procId, "mt-luva", {
      suggested_quantity: 2,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      sort_order: startOrder,
    }),
    link(`${procId}-mascara`, procId, "mt-mascara", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      sort_order: startOrder + 1,
    }),
    link(`${procId}-babador`, procId, "mt-babador", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      optional: true,
      sort_order: startOrder + 2,
    }),
    link(`${procId}-sugador`, procId, "mt-sugador", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      sort_order: startOrder + 3,
    }),
  ];
}

function restorationLinks(
  procId: string,
  resinQty: number,
): ProcedureTemplateMaterial[] {
  return [
    ...epiLinks(procId, 1),
    link(`${procId}-resina`, procId, "mt-resina", {
      suggested_quantity: resinQty,
      consumption_unit: "g",
      consumption_mode: "per_unit",
      notes: "Estimativa inicial para controle de estoque — editável",
      sort_order: 10,
    }),
    link(`${procId}-acido`, procId, "mt-acido", {
      suggested_quantity: 0.2,
      consumption_unit: "ml",
      consumption_mode: "per_procedure",
      notes: "Estimativa operacional",
      sort_order: 11,
    }),
    link(`${procId}-adesivo`, procId, "mt-adesivo", {
      suggested_quantity: 0.1,
      consumption_unit: "ml",
      consumption_mode: "per_procedure",
      notes: "Estimativa operacional",
      sort_order: 12,
    }),
    link(`${procId}-microbrush`, procId, "mt-microbrush", {
      suggested_quantity: 2,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 13,
    }),
    link(`${procId}-gaze`, procId, "mt-gaze", {
      suggested_quantity: 4,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 14,
    }),
    link(`${procId}-matriz`, procId, "mt-matriz", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 15,
    }),
    link(`${procId}-cunha`, procId, "mt-cunha", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 16,
    }),
    link(`${procId}-fio`, procId, "mt-fio-dental", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 17,
    }),
    link(`${procId}-carbono`, procId, "mt-papel-carbono", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 18,
    }),
    link(`${procId}-anest`, procId, "mt-anestesioco", {
      suggested_quantity: null,
      consumption_unit: "tubete",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 19,
    }),
    link(`${procId}-agulha`, procId, "mt-agulha-curta", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 20,
    }),
  ];
}

function perioLinks(procId: string): ProcedureTemplateMaterial[] {
  return [
    ...epiLinks(procId, 1),
    link(`${procId}-gaze`, procId, "mt-gaze", {
      suggested_quantity: 4,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    link(`${procId}-pasta`, procId, "mt-pasta-profilatica", {
      suggested_quantity: 1,
      consumption_unit: "g",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 11,
    }),
    link(`${procId}-microbrush`, procId, "mt-microbrush", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 12,
    }),
    link(`${procId}-anest`, procId, "mt-anestesioco", {
      suggested_quantity: null,
      consumption_unit: "tubete",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 13,
    }),
    link(`${procId}-agulha`, procId, "mt-agulha-curta", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 14,
    }),
  ];
}

function endoLinks(procId: string): ProcedureTemplateMaterial[] {
  return [
    ...epiLinks(procId, 1),
    link(`${procId}-gaze`, procId, "mt-gaze", {
      suggested_quantity: 6,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    link(`${procId}-anest`, procId, "mt-anestesioco", {
      suggested_quantity: null,
      consumption_unit: "tubete",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 11,
    }),
    link(`${procId}-agulha`, procId, "mt-agulha-longa", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 12,
    }),
    link(`${procId}-irrigante`, procId, "mt-irrigante", {
      suggested_quantity: null,
      consumption_unit: "ml",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Material variável — não é protocolo terapêutico",
      sort_order: 13,
    }),
    link(`${procId}-lima`, procId, "mt-lima-manual", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 14,
    }),
    link(`${procId}-provisorio`, procId, "mt-material-provisorio", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 15,
    }),
  ];
}

function surgeryLinks(procId: string): ProcedureTemplateMaterial[] {
  return [
    link(`${procId}-luva`, procId, "mt-luva", {
      suggested_quantity: 2,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      sort_order: 1,
    }),
    link(`${procId}-mascara`, procId, "mt-mascara", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_appointment",
      sort_order: 2,
    }),
    link(`${procId}-gaze`, procId, "mt-gaze", {
      suggested_quantity: 8,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 3,
    }),
    link(`${procId}-sugador`, procId, "mt-sugador-cirurgico", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 4,
    }),
    link(`${procId}-campo`, procId, "mt-campo", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 5,
    }),
    link(`${procId}-anest`, procId, "mt-anestesioco", {
      suggested_quantity: null,
      consumption_unit: "tubete",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 6,
    }),
    link(`${procId}-agulha`, procId, "mt-agulha-longa", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 7,
    }),
    link(`${procId}-sutura`, procId, "mt-fio-sutura", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      notes: "Quantidade a confirmar no atendimento",
      sort_order: 8,
    }),
    link(`${procId}-lamina`, procId, "mt-lamina", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      sort_order: 9,
    }),
  ];
}

export function buildProcedureTemplateMaterials(): ProcedureTemplateMaterial[] {
  const links: ProcedureTemplateMaterial[] = [
    // Profilaxia / prevenção com EPI
    ...epiLinks("pt-profilaxia", 1),
    link("pt-profilaxia-gaze", "pt-profilaxia", "mt-gaze", {
      suggested_quantity: 4,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    link("pt-profilaxia-pasta", "pt-profilaxia", "mt-pasta-profilatica", {
      suggested_quantity: 1,
      consumption_unit: "g",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 11,
    }),
    ...epiLinks("pt-consulta-inicial", 1),
    ...epiLinks("pt-urgencia", 1),
    ...epiLinks("pt-selante", 1),
    link("pt-selante-acido", "pt-selante", "mt-acido", {
      suggested_quantity: 0.1,
      consumption_unit: "ml",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    link("pt-selante-adesivo", "pt-selante", "mt-adesivo", {
      suggested_quantity: 0.05,
      consumption_unit: "ml",
      consumption_mode: "per_procedure",
      sort_order: 11,
    }),
    // Restaurações
    ...restorationLinks("pt-rest-pequena", 0.2),
    ...restorationLinks("pt-rest-media", 0.35),
    ...restorationLinks("pt-rest-extensa", 0.5),
    ...restorationLinks("pt-rest-anterior", 0.3),
    ...restorationLinks("pt-rest-cervical", 0.25),
    ...restorationLinks("pt-reconstrucao", 0.6),
    ...restorationLinks("pt-reparo-resina", 0.15),
    ...restorationLinks("pt-faceta-direta", 0.5),
    ...restorationLinks("pt-diastema", 0.3),
    ...epiLinks("pt-polimento-rest", 1),
    link("pt-polimento-disco", "pt-polimento-rest", "mt-disco-acabamento", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 10,
    }),
    link("pt-polimento-pasta", "pt-polimento-rest", "mt-pasta-polimento", {
      suggested_quantity: 0.5,
      consumption_unit: "g",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 11,
    }),
    // Periodontia
    ...perioLinks("pt-raspagem-supra"),
    ...perioLinks("pt-raspagem-sub"),
    ...perioLinks("pt-raspagem-quadrante"),
    ...perioLinks("pt-manutencao-perio"),
    ...perioLinks("pt-polimento-perio"),
    // Endodontia
    ...endoLinks("pt-acesso-endo"),
    ...endoLinks("pt-endo-uni"),
    ...endoLinks("pt-endo-bi"),
    ...endoLinks("pt-endo-multi"),
    ...endoLinks("pt-curativo-endo"),
    link("pt-curativo-mat", "pt-curativo-endo", "mt-curativo-intracanal", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 20,
    }),
    ...endoLinks("pt-retratamento"),
    ...endoLinks("pt-obturacao"),
    link("pt-obturacao-guta", "pt-obturacao", "mt-cone-guta", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 20,
    }),
    link("pt-obturacao-cimento", "pt-obturacao", "mt-cimento-obturador", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 21,
    }),
    // Cirurgia
    ...surgeryLinks("pt-exodontia-simples"),
    ...surgeryLinks("pt-exodontia-cirurgica"),
    ...surgeryLinks("pt-raiz-residual"),
    ...surgeryLinks("pt-terceiro-molar"),
    ...surgeryLinks("pt-sutura"),
    ...epiLinks("pt-remocao-sutura", 1),
    // Clareamento
    ...epiLinks("pt-clareamento-consultorio", 1),
    link("pt-clar-gel", "pt-clareamento-consultorio", "mt-gel-clareador", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      clinically_variable: true,
      notes: "Quantidade conforme produto utilizado pela clínica",
      sort_order: 10,
    }),
    link("pt-clar-barreira", "pt-clareamento-consultorio", "mt-barreira-gengival", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 11,
    }),
    link("pt-clar-micro", "pt-clareamento-consultorio", "mt-microbrush", {
      suggested_quantity: 2,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 12,
    }),
    link("pt-clar-gaze", "pt-clareamento-consultorio", "mt-gaze", {
      suggested_quantity: 4,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 13,
    }),
    ...epiLinks("pt-clareamento-caseiro", 1),
    link("pt-caseiro-moldeira", "pt-clareamento-caseiro", "mt-moldeira", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    ...epiLinks("pt-dessensibilizante", 1),
    link("pt-dess-mat", "pt-dessensibilizante", "mt-dessensibilizante", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      clinically_variable: true,
      sort_order: 10,
    }),
    // Prótese — EPI + variáveis
    ...epiLinks("pt-preparo-coroa", 1),
    link("pt-prep-fio", "pt-preparo-coroa", "mt-fio-retrator", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      sort_order: 10,
    }),
    ...epiLinks("pt-coroa-provisoria", 1),
    link("pt-prov-resina", "pt-coroa-provisoria", "mt-resina-provisoria", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 10,
    }),
    ...epiLinks("pt-moldagem", 1),
    link("pt-mold-silicone", "pt-moldagem", "mt-silicone", {
      suggested_quantity: null,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 10,
    }),
    link("pt-mold-alginato", "pt-moldagem", "mt-alginato", {
      suggested_quantity: null,
      consumption_unit: "g",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      sort_order: 11,
    }),
    ...epiLinks("pt-cimentacao-coroa", 1),
    link("pt-cim-def", "pt-cimentacao-coroa", "mt-cimento-definitivo", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    link("pt-cim-lab", "pt-cimentacao-coroa", "mt-laboratorio", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      notes: "Custo direto externo — registre o valor da clínica",
      sort_order: 11,
    }),
    ...epiLinks("pt-cimentacao-prov", 1),
    link("pt-cim-prov", "pt-cimentacao-prov", "mt-cimento-provisorio", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "per_procedure",
      sort_order: 10,
    }),
    // Implantes — EPI + manuais
    ...surgeryLinks("pt-instalacao-implante"),
    ...epiLinks("pt-reabertura", 1),
    ...epiLinks("pt-moldagem-implante", 1),
    ...epiLinks("pt-coroa-implante", 1),
    link("pt-coroa-imp-lab", "pt-coroa-implante", "mt-laboratorio", {
      suggested_quantity: 1,
      consumption_unit: "un",
      consumption_mode: "manual",
      clinically_variable: true,
      optional: true,
      sort_order: 10,
    }),
    // Odontopediatria
    ...epiLinks("pt-consulta-infantil", 1),
    ...epiLinks("pt-profilaxia-infantil", 1),
    link("pt-proph-inf-pasta", "pt-profilaxia-infantil", "mt-pasta-profilatica", {
      suggested_quantity: 1,
      consumption_unit: "g",
      consumption_mode: "per_procedure",
      optional: true,
      sort_order: 10,
    }),
    ...restorationLinks("pt-rest-infantil", 0.2),
    ...surgeryLinks("pt-exodontia-deciduo"),
    // Ortodontia básica
    ...epiLinks("pt-consulta-orto", 1),
    ...epiLinks("pt-manutencao-orto", 1),
    ...epiLinks("pt-colagem-bracket", 1),
    link("pt-bracket-adesivo", "pt-colagem-bracket", "mt-adesivo", {
      suggested_quantity: null,
      consumption_unit: "ml",
      consumption_mode: "manual",
      clinically_variable: true,
      sort_order: 10,
    }),
    ...epiLinks("pt-reposicao-bracket", 1),
  ];
  return links;
}
